version: '3.8'

services:
  app:
    image: todo-frontend-dev
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/src/app
    container_name: todo-frontend-dev