version: '3.8'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
    container_name: mongo-dev

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data
    container_name: redis-dev

  server:
    image: todo-backend-dev
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo-dev:27017/the_database
      - REDIS_URL=redis://redis-dev:6379
    volumes:
      - ./:/usr/src/app
    depends_on:
      - "mongo"
      - "redis"
    container_name: todo-backend-dev
